In [2]:
import pandas as pd 
diag_icd = pd.read_csv(r'C:\Users\sathv\OneDrive\Desktop\MIMIC DEMO\mimic-iv-clinical-database-demo-2.2\mimic-iv-clinical-database-demo-2.2\hosp\diagnoses_icd.csv.gz')

In [3]:
diag_icd.head(30)

    subject_id   hadm_id  seq_num icd_code  icd_version
0     10035185  22580999        3     4139            9
1     10035185  22580999       10     V707            9
2     10035185  22580999        1    41401            9
3     10035185  22580999        9     3899            9
4     10035185  22580999       11    V8532            9
5     10035185  22580999        2    25002            9
6     10035185  22580999        7    71696            9
7     10035185  22580999        8    V1083            9
8     10035185  22580999        4     2724            9
9     10035185  22580999        6    V5867            9
10    10035185  22580999        5    27800            9
11    10009049  22995465        2     4829            9
12    10009049  22995465        7    99592            9
13    10009049  22995465       13     2768            9
14    10009049  22995465        1     0388            9
15    10009049  22995465       11    78791            9
16    10009049  22995465        4     5601            9
17    10009049  22995465        5     2875            9
18    10009049  22995465        9    60001            9
19    10009049  22995465       12    79092            9
20    10009049  22995465        6     5110            9
21    10009049  22995465        8     2859            9
22    10009049  22995465        3     5849            9
23    10009049  22995465       10    78820            9
24    10009035  28324362        1     4240            9
25    10009035  28324362        4    V4589            9
26    10009035  28324362        2     5121            9
27    10009035  28324362        3     7873            9
28    10014729  23300884        3    99832            9
29    10014729  23300884       12    33812            9

In [5]:
diag_icd.shape

(4506, 5)

In [6]:
diag_icd.describe()

         subject_id       hadm_id      seq_num  icd_version
count  4.506000e+03  4.506000e+03  4506.000000  4506.000000
mean   1.001996e+07  2.520850e+07    11.163338     9.513316
std    1.232397e+04  2.931588e+06     8.200563     0.499878
min    1.000003e+07  2.004459e+07     1.000000     9.000000
25%    1.001087e+07  2.253930e+07     5.000000     9.000000
50%    1.001808e+07  2.517795e+07     9.000000    10.000000
75%    1.002929e+07  2.787622e+07    16.000000    10.000000
max    1.004002e+07  2.997458e+07    39.000000    10.000000

In [8]:
diag_icd.info()

<class 'pandas.DataFrame'>
RangeIndex: 4506 entries, 0 to 4505
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   subject_id   4506 non-null   int64
 1   hadm_id      4506 non-null   int64
 2   seq_num      4506 non-null   int64
 3   icd_code     4506 non-null   str
 4   icd_version  4506 non-null   int64
dtypes: int64(4), str(1)
memory usage: 176.1 KB